# OpenCV Configuration
# This file contains all OpenCV-specific build settings

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)

# imgcodecs is required for videoio (even without image file I/O)
set(BUILD_LIST "core,imgproc,imgcodecs,videoio" CACHE STRING "" FORCE)

set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_PERF_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(BUILD_opencv_apps OFF CACHE BOOL "" FORCE)
set(BUILD_opencv_java OFF CACHE BOOL "" FORCE)
set(BUILD_opencv_python OFF CACHE BOOL "" FORCE)
set(BUILD_opencv_gapi OFF CACHE BOOL "" FORCE)

set(WITH_FFMPEG ON CACHE BOOL "" FORCE)
set(WITH_GSTREAMER ON CACHE BOOL "" FORCE)

set(WITH_GTK OFF CACHE BOOL "" FORCE)
set(WITH_QT OFF CACHE BOOL "" FORCE)
set(WITH_OPENGL OFF CACHE BOOL "" FORCE)
set(WITH_OPENCL OFF CACHE BOOL "" FORCE)
set(WITH_CUDA OFF CACHE BOOL "" FORCE)
set(WITH_IPP OFF CACHE BOOL "" FORCE)
set(WITH_EIGEN OFF CACHE BOOL "" FORCE)
set(WITH_LAPACK OFF CACHE BOOL "" FORCE)
set(WITH_PROTOBUF OFF CACHE BOOL "" FORCE)
set(WITH_FLATBUFFERS OFF CACHE BOOL "" FORCE)

set(ENABLE_LIBJPEG_TURBO_SIMD OFF CACHE BOOL "" FORCE)

set(WITH_TBB OFF CACHE BOOL "" FORCE)

set(BUILD_ITT OFF CACHE BOOL "" FORCE)
set(OPENCV_ENABLE_NONFREE OFF CACHE BOOL "" FORCE)
set(BUILD_PACKAGE OFF CACHE BOOL "" FORCE)
set(WITH_1394 OFF CACHE BOOL "" FORCE)
set(WITH_VTK OFF CACHE BOOL "" FORCE)
set(WITH_QUIRC OFF CACHE BOOL "" FORCE)
set(ENABLE_FAST_MATH ON CACHE BOOL "" FORCE)
set(CV_ENABLE_INTRINSICS OFF CACHE BOOL "" FORCE)
